spring:
  application:
    name: letterboxd

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never

  thymeleaf:
    cache: false

server:
  port: ${PORT:8080}